global using Microsoft.Extensions.Logging;
global using System.Collections.ObjectModel;
global using System.Diagnostics.Tracing;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Maui;
global using VendyGoPizza.MAUI.Models;
global using VendyGoPizza.MAUI.Services;
global using VendyGoPizza.MAUI.ViewModels;
global using VendyGoPizza.MAUI.Views;